[package]
name = "texpresso"
version = "0.0.3"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
